[mcp_servers.aws-mcp]
url = "https://aws-mcp.us-east-1.api.aws/mcp"
enabled = true
default_tools_approval_mode = "prompt"

[mcp_servers.terraform-mcp]
command = "docker"
args = [
  "run",
  "-i",
  "--rm",
  "hashicorp/terraform-mcp-server"
]
enabled = true
default_tools_approval_mode = "prompt"

[mcp_servers.aws-serverless-mcp]
command = "uvx"
args = [
  "awslabs.aws-serverless-mcp-server@latest"
]
env = {
  AWS_PROFILE = "default",
  AWS_REGION = "us-east-1",
  FASTMCP_LOG_LEVEL = "ERROR"
}
enabled = true
default_tools_approval_mode = "prompt"
